config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root "home#index"

  get    "sign_up", to: "users#new",    as: "sign_up"
  post   "sign_up", to: "users#create"

  get    "sign_in", to: "sessions#new", as: "sign_in"
  post   "sign_in", to: "sessions#create"
  delete "sessions/destroy",            as: "sign_out"


  put "lists/:id/", to: "lists#archive", as: "archive_list"
  resources :users, only: [:create, :edit, :update]
  resources :lists, only: [:index, :show, :new, :create, :edit, :update, :destroy, :archive_index]

  patch "list/:list_id/task/:id/", to: "tasks#complete", as: "complete_task"
  get  "list/archive", to: "lists#archive_index", as: "archive"
  get  "complete/tasks/:id/", to: "lists#completed_tasks", as: "completed_tasks"

  resources "list" do
    resources :tasks
  end

  post "list/:id/archive", to: "lists#archive", as: "list_archive"
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user
  has_many :tasks, dependent: :destroy
  # scope :unarchived, -> { where(archived: false) }
  scope :unarchived, ->(user = nil) { where(archived: false, user: user) }
  scope :archived, ->(user) { where(archived: true, user: user) }


  def incomplete_tasks
    tasks.incomplete
  end

  def complete_tasks
    tasks.complete
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  validates_presence_of :list
  scope :incomplete, -> { where(complete: false) }
  scope :complete, -> { where(complete: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @lists = List.unarchived(current_user)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @list = List.new
    @lists = List.unarchived(current_user)
  end

  def archive_index
    @lists = List.archived(current_user)
  end

  def completed_tasks
    @list = List.find(params[:id])
  end

  def archive
    list = List.find(params[:id])
    list.update_attributes(archived: params[:archived])
    redirect_to root_path, alert: "#{list.title} has been archived"
  end

  def create
    list = List.new(title: list_params[:title], user: current_user)
    if list.save
      redirect_to :back
    else
      redirect_to :back, alert: "Oh no, that didn't quite work, try again."
    end
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update_attributes(update_list_params)
    redirect_to list_path(params[:id])
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to :back, notice: "#{list.title} has been Deleted"
  end

  private

  def list_params
    params.permit(:title)
  end

  def update_list_params
    params.require(:list).permit(:id, :title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
      user = User.find_by_email(params[:user][:email])
      login(user)
  end

  def destroy
    flash[:success] = "Were going to miss you. | You have successfully signed out."
    session.clear
    redirect_to root_path
  end

  private

  def login(user)
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome back #{user.name}!"
      redirect_to root_path
    else
      flash[:danger] = "Invalid login."
      render(:new)
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    if task.save
     new_task_mailer(task) if email_check(task)
      redirect_to list_path(params[:list_id])
    else
      redirect_to :back, notice: "Please include a Title and Discription"
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update_attributes(update_task_params)
    redirect_to list_path(task.list_id)
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to :back, notice: "#{task.title} has been Delted"
  end

  def complete
    task = Task.find(params[:id])
    if email_check(task)
      complete_task_mailer(task) if params[:complete] == "true"
      incomplete_task_mailer(task) if params[:complete] == "false"
    end
    task.update_attributes(complete: params[:complete])
    redirect_to :back, notice: "#{task.title} marked complete"
  end

  private

  def task_params
    params.permit(:title, :description, :list_id, :due_date)
  end

  def update_task_params
    params.require(:task).permit(:title, :description, :list_id)
  end

  def new_task_mailer(task)
     email = task.title.scan(/\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\b/)
     TaskMailer.new_task_notice(current_user, email, task).deliver
  end

  def complete_task_mailer(task)
     email = task.title.scan(/\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\b/)
     TaskMailer.complete_task_notice(current_user, email, task).deliver
  end

  def incomplete_task_mailer(task)
     email = task.title.scan(/\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\b/)
     TaskMailer.incomplete_task_notice(current_user, email, task).deliver
  end

  def email_check(task)
    task.title.split.grep(/\/cc/).any?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path, notice: "Welcome #{user.name}"
    else
      redirect_to :back, notice: "Please enter valid information"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update_attributes(user_params)
    redirect_to root_path, notice: "You have successfuly updated you info"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    case flash_type
    when :success
      "alert-success"
    when :danger
      "alert-danger"
    when :warning
      "alert-warning"
    when :info
      "alert-info"
    else
      flash_type.to_s
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_active_tasks.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <td class="value h4">Title</td>
      <td class="value h4">Description</td>
      <td class="value h4">Due Date</td>
      <td><%= link_to "View Completed", completed_tasks_path(list.id), class: "btn btn-default" %></td>
    </tr>
  </thead>
  <tbody>
  <% list.incomplete_tasks.each do |task| %>
    <tr>
      <td><%= link_to task.title, edit_list_task_path(list_id: list.id, id: task.id) %></td>
      <td><%= task.description %></td>
      <td><%= task.due_date %></td>
      <td><%= button_to "Complete", complete_task_path(list_id: list.id, id: task.id, complete: true), method: "patch", class: "btn btn-info" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/application/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type.to_sym) %> fade in">
    <%= message %>
  </div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button"
        class="navbar-toggle collapsed"
        data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1">

        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <h2><%= link_to "Task Track", root_path %></h2>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "View Archive", archive_path %></li>
          <li><%= link_to "New Task", lists_path %></li>
          <li><%= link_to "Sign Out", sign_out_path, method: :delete %></li>
          <li><%= link_to "Profile", edit_user_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Sign In", sign_in_path %></li>
          <li><%= link_to "Sign Up", sign_up_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/application/_new_list_form.html.erb
<div class="well">
  <div class="text-center">
    <span class="list-group-item active form-inline">
      <%= form_tag "/lists", method: "post" do %>
        <%= text_field_tag :title, nil, placeholder: "List title", class: "form-control" %>
      <%= submit_tag "Submit", name: nil, class: "btn" %>
    <% end %>
    </span>
  </div>
</div>

app/views/home/_no_lists.html.erb
<div class="container">
  <div class="row">
    <div class="col col-sm-6 col-sm-offset-3">
      <h1 class="text-center">Create your first list!</h1>
      <%= render partial: "new_list_form" %>
    </div>
  </div>
</div>

app/views/home/_task_lists.html.erb
<div class="row">
    <%= render partial: "no_lists" if @lists.count == 0 %>
  <div class="col col-sm-8 col-sm-offset-2">
    <% @lists.each do |list| %>
      <div class="panel panel-default">
      <div class="panel-heading">
        <h2><%= link_to list.title, list_path(list) %>
        <span class="pull-right">
          <%= link_to "New Task", new_list_task_path(list.id), class: "btn btn-primary form-inline" %>
        </span>
        <span class="pull-right">
          <%= button_to 'Move List to Archive', archive_list_path(list.id, archived: true), method: "put", class: "btn btn-default" %>
        </span>
        </h2>
    </div>
    <%= render partial: "active_tasks", locals: { list: list } %>
    </div>
    <% end %>
  </div>
</div>

app/views/home/_welcome_signup.html.erb
<div class="container">
  <div class="row">
    <div class="col col-sm-6 col-sm-offset-3">
      <h1 class="text-center">Welcome to Task Track</h1>
      <div class="well">
        <div class="text-center">
          <%= link_to "Please Sign Up", sign_up_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% if current_user %>
  <%= render partial: "task_lists" %>
<% else %>
  <%= render partial: "welcome_signup" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "navbar" %>

<div class="col col-sm-8 col-sm-offset-2">
  <%= render partial: "flash_messages", flash: flash %>
</div>

<%= yield %>

</body>
</html>

app/views/lists/archive_index.html.erb
<div class="row">
  <div class="col col-sm-8 col-sm-offset-2">
    <% @lists.each do |list| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2><%= link_to list.title, list_path(list) %>
          <span class="pull-right">
            <%= button_to "Delete List",
              "/lists/#{list.id}",
              method: "delete",
              class: "btn btn-danger form-inline" %>
          </span>
          <span class="pull-right">
            <%= button_to 'Unarchive List',
              archive_list_path(list.id, archived: false),
              method: "put",
              class: "btn btn-default" %>
          </span>
          </h2>
        </div>
        <%= render partial: "active_tasks", locals: { list: list } %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/completed_tasks.html.erb
<div class="row">
  <div class="col col-sm-8 col-sm-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading inline-block">
        <h2><%= @list.title %> Completed Tasks
        <%= link_to "Add Task", new_list_task_path(@list.id),
          class: "btn btn-primary form-inline pull-right" %></h2>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <td class="value h4">Title</td>
            <td class="value h4">Description</td>
            <td class="value h4">Due Date</td>
            <td><%= link_to "View Incomplete", list_path(@list.id), class: "btn btn-default" %></td>
          </tr>
        </thead>
        <tbody>
        <% @list.complete_tasks.each do |task| %>
          <tr>
            <td><%= task.title %></td>
            <td><%= task.description %></td>
            <td><%= task.due_date %></td>
            <td><%= link_to "Incomplete",
              complete_task_path(list_id: @list.id,
                                 id: task.id,
                                 complete: false),
              method: "patch",
              class: "btn btn-default pull-right" %>
            <%= link_to "Delete", "/list/#{@list.id}/tasks/#{task.id}", method: "delete", class: "btn btn-warning pull-right" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/lists/edit.html.erb
<div class="row">
  <div class="col col-sm-4 col-sm-offset-4">
    <div class="panel panel-default">
      <div class="panel-heading inline-block">
        <h2>Edit List</h2>
      </div>
      <div class="panel-body">
        <div class="input-group">
        <%= simple_form_for @list, method: "patch" do |f| %>
          <%= f.input :title %>
          <%= f.submit %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="row">
  <div class="col col-sm-6 col-sm-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">To add a task, please choose a list or create a new one.</div>
      <%= render partial: "new_list_form" %>
      <ul class="list-group">
      <% @lists.each do |list| %>
        <li class="list-group-item"><h4><%= link_to list.title, new_list_task_path(list.id), class: "panel-body" %></h4></li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="row">
  <div class="col col-sm-8 col-sm-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading inline-block">
        <h2><%= link_to @list.title, edit_list_path(@list) %>
        <span class="pull-right">
        <%= link_to "Add Task", new_list_task_path(@list.id),
          class: "btn btn-primary form-inline pull-right" %>
        </span>
        <span class="pull-right">
          <%= button_to 'Move List to Archive', archive_list_path(@list.id, archived: true), method: "put", class: "btn btn-default" %></h2>
        </span>
      </div>
      <%= render partial: "active_tasks", locals: { list: @list } %>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col col-sm-4 col-sm-offset-4">
    <div class="panel panel-default">
      <div class="panel-heading inline-block">
        <h2>Add a task</h2>
      </div>
      <div class="panel-body">
        <div class="input-group">
        <%= form_tag "/list/#{params[:list_id]}/tasks", method: "post" do %>
          <%= text_field_tag :title, nil, placeholder: "Task Title", class: "form-control" %>
           <%= text_field_tag :description, nil, placeholder: "Task Description", class: "form-control"  %>
           <%= date_field_tag "due_date", nil, class: "form-control" %>
          <%= submit_tag "Submit", name: nil, class: "btn" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="row">
  <div class="col col-sm-4 col-sm-offset-4">
    <div class="panel panel-default">
      <div class="panel-heading inline-block">
        <h2>Edit Task</h2>
      </div>
      <div class="panel-body">
        <div class="input-group">
          <%= form_for @task, url: "/list/#{@task.list_id}/tasks/#{@task.id}" do |f| %>
          <%= f.text_field :title, class: "form-control" %>
          <%= f.text_field :description, class: "form-control" %>
          <%= f.date_field :due_date, class: "form-control" %>
          <%= f.submit class: "btn" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<%= render partial: "form" %>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :name, label: 'Your name please' %>
  <%= f.input :password, hint: 'No special characters.' %>
  <%= f.input :email, placeholder: 'user@example.com' %>
  <%= f.button :submit %>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col col-sm-6 col-sm-offset-3">
    <h2>Edit Your Stuff</h2>
  </div>
</div>
<div class="row">
  <div class="col col-sm-6 col-sm-offset-3">
    <div class="well">
      <%= render partial: "form" %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col col-sm-6 col-sm-offset-3">
    <h2>Sign Up</h2>
  </div>
</div>
<div class="row">
  <div class="col col-sm-6 col-sm-offset-3">
    <div class="well">
      <%= render partial: "form" %>
    </div>
  </div>
</div>